"""Handles drift ignore filtering based on GNU Stow matching logic using pathlib."""

import re
import logging
from pathlib import Path
from typing import List, Optional, Protocol, runtime_checkable

from .constants import (
    MANAGED_CONFIG_FILES,
    DRIFT_IGNORE_FILE_NAME,
    DRIFT_IGNORE_FILE_NAME_LIST,
    DEFAULT_STOW_IGNORE_PATTERNS,
)

logger = logging.getLogger(__name__)


@runtime_checkable
class IgnoreHandler(Protocol):
    """Protocol for ignore path matching."""

    def match_path(self, rel_path: Path) -> bool:
        """Determines whether a relative path should be ignored.

        Args:
            rel_path: Relative Path object to check against ignore rules.

        Returns:
            True if the path should be ignored, False otherwise.
        """
        ...


class DriftIgnore(IgnoreHandler):
    """Handles parsing and match evaluation of drift ignore patterns."""

    def __init__(self, patterns: Optional[List[str]] = None) -> None:
        if patterns is None:
            self.patterns = list(DEFAULT_STOW_IGNORE_PATTERNS)
        else:
            self.patterns = list(patterns)
        # Pre-divide patterns depending on whether they contain '/'
        self.set_with_slash = []
        self.set_without_slash = []
        for pattern in self.patterns:
            if "/" in pattern:
                self.set_with_slash.append(pattern)
            else:
                self.set_without_slash.append(pattern)

    @staticmethod
    def strip_comments(line: str) -> str:
        """Strips out comments unless '#' is escaped with a backslash."""
        result = []
        escaped = False
        for char in line:
            if char == "\\" and not escaped:
                escaped = True
                result.append(char)
                continue
            if char == "#" and not escaped:
                break
            escaped = False
            result.append(char)
        return "".join(result).strip()

    @classmethod
    def load_from_dir(cls, render_pkg_dir: Path) -> "DriftIgnore":
        """
        Loads ignore PCRE regex patterns from .drift_ignore inside render_pkg_dir.
        Returns an instance of DriftIgnore with the loaded patterns.
        If the file does not exist, returns an instance with the default Stow ignore patterns.
        """
        if not render_pkg_dir.exists() or not render_pkg_dir.is_dir():
            return cls(None)

        # Proactively check for nested ignore files in subdirectories
        for ignore_name in DRIFT_IGNORE_FILE_NAME_LIST:
            for path in render_pkg_dir.rglob(ignore_name):
                # Ensure the path is inside a subdirectory, not at the root
                if path.parent != render_pkg_dir:
                    raise ValueError(
                        f"Nested ignore files are not allowed. "
                        f"Found nested '{ignore_name}' inside subdirectory: "
                        f"{path.parent.relative_to(render_pkg_dir)}"
                    )

        ignore_path = render_pkg_dir / DRIFT_IGNORE_FILE_NAME
        if not ignore_path.exists() or not ignore_path.is_file():
            return cls(None)
        patterns = []
        with ignore_path.open("r", encoding="utf-8") as f:
            for line in f:
                line_stripped = cls.strip_comments(line)
                if line_stripped:
                    patterns.append(line_stripped)
        return cls(patterns)

    def export_stow_ignore_patterns(self) -> List[str]:
        """Exports the list of ignore patterns combined with MANAGED_CONFIG_FILES in Stow format."""
        exported = []
        # 1. Add MANAGED_CONFIG_FILES patterns with escaped dots
        for managed_file in MANAGED_CONFIG_FILES:
            escaped_name = managed_file.replace(".", r"\.")
            pattern = f"^/{escaped_name}$"
            if pattern not in exported:
                exported.append(pattern)
        # 2. Add patterns from DriftIgnore
        for p in self.patterns:
            if p not in exported:
                exported.append(p)
        return exported

    def generate_stow_local_ignore_content(self) -> str:
        """Generates the content for a .stow-local-ignore file."""
        lines = [
            "# =====================================================================",
            "# .stow-local-ignore - Generated by Drift for GNU Stow compatibility",
            "# =====================================================================",
        ]
        lines.extend(self.export_stow_ignore_patterns())
        return "\n".join(lines) + "\n"


    def filter_deployable_files(self, install_pkg_dir: Path) -> List[Path]:
        """
        Returns a list of relative Path objects for all deployable files in a package.
        The install_pkg_dir is the path to the package in the install directory.
        The input should not contain any symlink to other directories.
        The returned list excludes files that match the ignore patterns.
        """
        from .file_utils import tree_relative_files
        return [ rel_file for rel_file in tree_relative_files(install_pkg_dir)
                if rel_file.name not in MANAGED_CONFIG_FILES
                    and not self.match_path(rel_file) ]


    def match_path(self, rel_path: Path) -> bool:
        """Implements GNU Stow's ignore matching algorithm on a relative path."""
        # Special exception: always ignore ignore-related files and config files
        filename = rel_path.name
        if filename in MANAGED_CONFIG_FILES:
            return True

        normalized_rel_path = rel_path.as_posix()
        path_with_slash = "/" + normalized_rel_path
        basename = rel_path.name

        # Match Step 1: Check patterns containing '/' against path_with_slash
        for pattern in self.set_with_slash:
            try:
                if re.search(pattern, path_with_slash):
                    return True
            except re.error as e:
                logger.warning(f"Invalid regex pattern '{pattern}': {e}")

        # Match Step 2: Check remaining patterns against basename
        for pattern in self.set_without_slash:
            try:
                if re.search(pattern, basename):
                    return True
            except re.error as e:
                logger.warning(f"Invalid regex pattern '{pattern}': {e}")

        return False
