#!/usr/bin/env bash
# =============================================================================
# Drift CLI - Shell Wrapper Installer
# =============================================================================
# Installs a lightweight executable wrapper script for Drift into ~/.local/bin.
# This allows running 'drift' globally without requiring virtual environments
# or third-party package managers.
# =============================================================================

set -euo pipefail

# Default configuration
DEFAULT_BIN_DIR="${HOME}/.local/bin"
TARGET_BIN_DIR="${DEFAULT_BIN_DIR}"
FORCE=false

print_usage() {
    cat << EOF
Usage: $(basename "$0") [OPTIONS]

Installs a shell wrapper for the 'drift' command into ~/.local/bin.

Options:
  -f, --force         Overwrite any existing 'drift' executable or wrapper
  -d, --dir <DIR>     Custom destination directory (default: ~/.local/bin)
  -h, --help          Display this help message and exit

EOF
}

# Parse command-line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        -f|--force)
            FORCE=true
            shift
            ;;
        -d|--dir)
            if [[ -z "${2:-}" ]]; then
                echo "❌ [ERROR] Option '$1' requires a directory argument." >&2
                exit 1
            fi
            TARGET_BIN_DIR="$2"
            shift 2
            ;;
        -h|--help)
            print_usage
            exit 0
            ;;
        *)
            echo "❌ [ERROR] Unknown option: $1" >&2
            print_usage >&2
            exit 1
            ;;
    esac
done

# Resolve absolute paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
DRIFT_REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd -P)"
DRIFT_SRC_DIR="${DRIFT_REPO_ROOT}/src"

# Verify repository structure
if [[ ! -d "${DRIFT_SRC_DIR}/drift" ]]; then
    echo "❌ [ERROR] Cannot locate Drift source directory at '${DRIFT_SRC_DIR}/drift'." >&2
    exit 1
fi

# Expand destination path (handling ~ if passed as string)
TARGET_BIN_DIR="${TARGET_BIN_DIR/#\~/$HOME}"
TARGET_BIN_DIR="$(mkdir -p "${TARGET_BIN_DIR}" && cd "${TARGET_BIN_DIR}" && pwd -P)"
WRAPPER_PATH="${TARGET_BIN_DIR}/drift"

# Check if 'drift' is already available in PATH
EXISTING_DRIFT="$(command -v drift 2>/dev/null || true)"

if [[ -n "${EXISTING_DRIFT}" && "${FORCE}" = false ]]; then
    echo "✨ 'drift' command is already available in PATH at:"
    echo "   ${EXISTING_DRIFT}"
    echo
    echo "💡 To reinstall or overwrite the wrapper in '${WRAPPER_PATH}', run with --force:"
    echo "   $0 --force"
    exit 0
fi

# Create target directory
mkdir -p "${TARGET_BIN_DIR}"

# Generate wrapper script
cat << EOF > "${WRAPPER_PATH}"
#!/usr/bin/env bash
# =============================================================================
# Drift CLI Shell Wrapper
# Generated by: script/shell_wrapper_installer.bash
# Drift Source: ${DRIFT_SRC_DIR}
# =============================================================================
set -e

DRIFT_SRC="${DRIFT_SRC_DIR}"

# Locate Python interpreter (Python >= 3.8 supported)
if command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN="python3"
elif command -v python >/dev/null 2>&1; then
    PYTHON_BIN="python"
else
    echo "❌ [ERROR] Python 3 interpreter (python3 or python) is required to run Drift." >&2
    exit 1
fi

export PYTHONPATH="\${DRIFT_SRC}\${PYTHONPATH:+:\${PYTHONPATH}}"
exec "\${PYTHON_BIN}" -m drift "\$@"
EOF

# Make wrapper executable
chmod +x "${WRAPPER_PATH}"

echo "🎉 Successfully installed Drift shell wrapper to:"
echo "   ${WRAPPER_PATH}"
echo

# Check if TARGET_BIN_DIR is currently in PATH
PATH_NORMALIZED=":${PATH}:"
if [[ "${PATH_NORMALIZED}" != *":${TARGET_BIN_DIR}:"* ]]; then
    echo "⚠️  [NOTE] '${TARGET_BIN_DIR}' is not currently in your \$PATH."
    echo "   To make 'drift' available in all terminal sessions, add the following line"
    echo "   to your shell profile (~/.bashrc, ~/.zshrc, or ~/.bash_profile):"
    echo
    echo "   export PATH=\"${TARGET_BIN_DIR}:\$PATH\""
    echo
fi

echo "🚀 You can now run: ${WRAPPER_PATH} --help"
